# Generated by Django 5.0 on 2024-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('waranty', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
